# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'OCCalculator' do
pod 'SDAutoLayout'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OCCalculator

  target 'OCCalculatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OCCalculatorUITests' do
    # Pods for testing
  end

end
